# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsignatura', models.CharField(max_length=250)),
                ('claveAsignatura', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=250)),
                ('sigla', models.CharField(max_length=20)),
                ('universidad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=20)),
                ('fono', models.CharField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion_Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(max_length=20)),
                ('semestre', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaAsignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.CharField(max_length=20)),
                ('semestre', models.CharField(max_length=20)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='MallaCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMalla', models.CharField(max_length=250)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.Carrera')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion_asignatura',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.InstanciaAsignatura'),
        ),
        migrations.AddField(
            model_name='inscripcion_asignatura',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.Estudiante'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='mallaCurricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.MallaCurricular'),
        ),
    ]
