# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navegadorcito3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion_asignatura',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='inscripcion_asignatura',
            name='semestre',
        ),
    ]
