# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegadorcito3', '0002_auto_20170924_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion_asignatura',
            name='estado',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
