# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navegadorcito3', '0003_auto_20170924_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instanciaasignatura',
            name='anno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instanciaasignatura',
            name='semestre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
