# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navegadorcito3', '0005_auto_20170925_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula_Malla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.Estudiante')),
                ('malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.MallaCurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dniP', models.CharField(max_length=20, unique=True)),
                ('passwordP', models.CharField(max_length=20, null=True)),
                ('nombreP', models.CharField(max_length=20)),
                ('apellidoP', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='instanciaasignatura',
            name='profe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='navegadorcito3.Profesor'),
            preserve_default=False,
        ),
    ]
